sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
 - "3.4"

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libgeos-dev
    - libhdf5-serial-dev

install:
  - pip install scipy cython shapely psutil h5py
  - python setup.py develop

script:
  - python setup.py test
