sudo: false

# We are using our own python
language: c

addons:
  apt:
    packages:
    - wget
    - git

before_install:
  - wget http://ftp.openquake.org/travis/openquake-env-setup-py3-precise64.run
  - chmod +x openquake-env-setup-py3-precise64.run

env:
    LD_LIBRARY_PATH=$HOME/openquake/lib
    PATH=$HOME/openquake/bin:$PATH

install:
  - ./openquake-env-setup-py3-precise64.run -- -d ~
  - git clone -b python3 --depth=1 https://github.com/gem/oq-hazardlib.git

# We must set the PYTHONPATH to the root oq-engine (insted of oq-engine/openquake) because otherwise
# the full 'openquake' namespace is overwritten and then hazardlib and baselib are not found
script:
  # FIXME --with-doctest does not work
  # - PYTHONPATH=. nosetests -vsx -a'!slow' --with-xunit --nologcapture
  - PYTHONPATH=.:$HOME/oq-hazardlib nosetests -v -a'!slow'
