sudo: false

language: python

python:
 - "3.5"

addons:
  apt:
    packages:
    - wget

before_install:
  - wget http://ftp.openquake.org/travis/openquake-env-setup-py3-linux64.run

env:
    LD_LIBRARY_PATH=$HOME/openquake/lib
    PATH=$HOME/openquake/lib:$PATH

install:
  - ./openquake-env-setup-py3-linux64.run -- -d ~
  - pip install https://github.com/gem/oq-hazardlib/archive/python3.zip
  - pip install .

script:
  - nosetests -vsx -a'!slow' --with-xunit --nologcapture --with-doctest
