sudo: false

language: python

python:
 - "2.7"

addons:
  apt:
    packages:
    - sed
    - git

install:
  - git clone --depth=1 https://github.com/gem/oq-hazardlib.git
  - git clone --depth=1 https://github.com/gem/oq-engine.git
  - pip install -U pip
  - pip install -r oq-engine/requirements-py27-linux64.txt

script:
  - PYTHONPATH=$(pwd)/oq-hazardlib:$(pwd)/oq-engine:. nosetests -vx tests
