sudo: false

language: python

python:
 - "3.4"

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libgeos-dev

install:
  - python setup.py develop

script:
  python setup.py test
