sudo: false

language: python

python:
 - "2.7"

addons:
  apt:
    packages:
    - cython
    - gfortran
    - liblapack-dev
    - python-numpy
    - python-scipy
    - libgeos-dev
    - libhdf5-dev

install:
  - pip install psutil shapely h5py
  - python setup.py install

script:
  nosetests -a'!slow' -vx
