sudo: false

language: python

python:
 - "3.4"

addons:
  apt:
    packages:
    - libgeos-dev

install:
  - pip install https://dl.dropboxusercontent.com/u/418677/scipy-0.16.0-cp34-cp34m-linux_x86_64.whl
  - pip install https://dl.dropboxusercontent.com/u/418677/h5py-2.5.0-cp34-cp34m-linux_x86_64.whl
  - python setup.py develop

script:
  - python setup.py test
