sudo: false

language: python

python:
 - "3.5"

addons:
  apt:
    packages:
    - git

install:
  - pip install http://ftp.openquake.org/python-new-wheels/Cython-0.23.4-cp35-cp35m-manylinux1_x86_64.whl
  - pip install http://ftp.openquake.org/python-new-wheels/numpy-1.11.1-cp35-cp35m-manylinux1_x86_64.whl
  - pip install http://ftp.openquake.org/python-new-wheels/scipy-0.17.1-cp35-cp35m-manylinux1_x86_64.whl
  - pip install http://ftp.openquake.org/python-new-wheels/Shapely-1.5.13-cp35-cp35m-manylinux1_x86_64.whl
  - pip install http://ftp.openquake.org/python-new-wheels/h5py-2.6.0-1-cp35-cp35m-manylinux1_x86_64.whl
  - pip install -r requirements-dev.txt
  - python setup.py develop
  - git clone --depth=1 https://github.com/gem/oq-hazardlib.git

# We must set the PYTHONPATH to the root oq-engine (insted of oq-engine/openquake) because otherwise
# the full 'openquake' namespace is overwritten and then hazardlib and baselib are not found
script:
  # FIXME --with-doctest does not work
  # - PYTHONPATH=. nosetests -vsx -a'!slow' --with-xunit --nologcapture
  - PYTHONPATH=.:$(pwd)/oq-hazardlib nosetests -v -a'!slow'
