sudo: false

language: python

cache: pip

python:
 - "3.4"

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libgeos-dev

install:
  - pip install scipy shapely psutil
  - python setup.py develop

script:
  - python setup.py test
