sudo: false

language: python

python:
 - "2.7"

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libgeos-dev

install:
  - python setup.py install

script:
  ls
  nosetests -vx openquake
