sudo: false

language: python

python:
 - "3.5"

jobs:
  include:
  - stage: demos
    script: 
        - bin/run-demos.sh
  - stage: tests
    script:
        - nosetests --with-doctest -xs -a'!slow' openquake.engine
        - mkdir ~/oqdata; nosetests --with-doctest -xs -a'!slow' openquake.server
        - bin/oq webui migrate
        - cat /tmp/webui*
    after_success:
        - pip install sphinx==1.3.6 && cd doc/sphinx && make html
  - stage: tests
    script:
        - nosetests --with-doctest -xs -a'!slow' openquake.hazardlib 
  - stage: tests
    script:
        - nosetests --with-doctest -xs -a'!slow' openquake.risklib
  - stage: tests
    script:
        - nosetests --with-doctest -xs -a'!slow' openquake.commonlib
        - nosetests --with-doctest -xs -a'!slow' openquake.commands
  - stage: tests
    script:
        - nosetests --with-doctest -xs -a'!slow' openquake.hmtk

install:
  - pip install -r requirements-py35-linux64.txt
  - pip install -e .

before_script:
  - python -c'import platform; print(platform.platform())'

after_script:
  - bin/oq reset --yes
