sudo: false

language: python

python:
 - "3.5"

addons:
  apt:
    packages:
    - git

install:
  - pip install -r requirements-py35-linux64.txt
  - python setup.py develop
  - git clone --depth=1 https://github.com/gem/oq-hazardlib.git

# We must set the PYTHONPATH to the root oq-engine (insted of oq-engine/openquake) because otherwise
# the full 'openquake' namespace is overwritten and then hazardlib and baselib are not found
script:
  # FIXME --with-doctest does not work
  # - PYTHONPATH=. nosetests -vsx -a'!slow' --with-xunit --nologcapture
  - PYTHONPATH=.:$(pwd)/oq-hazardlib nosetests -v -a'!slow'
