sudo: false

language: python

python:
 - "2.7"

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-psutil
    - python-shapely
    - python-h5py

install:
  - python setup.py install

script:
  nosetests -a'!slow' -vx
