sudo: false

language: python

python:
 - "3.5"

addons:
  apt:
    packages:
    - git

install:
  - pip install -r requirements-py35-linux64.txt
  - pip install -e .

script:
  - python -c'import platform; print(platform.platform())'
  - bin/run-demos.sh
  - nosetests --with-doctest -vsx -a'!slow'
  - cat /tmp/webui*
  - bin/oq reset --yes

after_success:
  - pip install sphinx==1.3.6
  - cd doc/sphinx
  - make html
