sudo: false

language: python

python:
 - "3.4"

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libgeos-dev

install:
  - pip install psutil shapely
  - python setup.py install

script:
  cd .. && python -m unittest discover oq-hazardlib/openquake -p *test.py
