sudo: false

language: python

python:
 - "2.7"

addons:
  apt:
    packages:
    - git

install:
  # Clone oq-hazardlib
  - if [ "$(git ls-remote --heads https://github.com/gem/oq-hazardlib.git ${TRAVIS_BRANCH})" != "" ]; then BRANCH=$TRAVIS_BRANCH; else BRANCH='master'; fi; git clone -b ${BRANCH} --depth=1 https://github.com/gem/oq-hazardlib.git && echo "Running on oq-hazardlib/${BRANCH}"
  # Make sure pip is up-to-date and has support for wheels
  - pip install -U pip
  # Install oq-hazardlib dependencies
  - pip install -r oq-hazardlib/requirements-py27-linux64.txt
  # Install HMTK extra dependencies
  - pip install -r requirements-py27-linux64.txt
  - pip install oq-hazardlib
  - pip install .

script:
  - nosetests -vx tests
