sudo: false

language: python

cache:
  directories:
    - $HOME/pkgcache

python:
 - "3.4"

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libgeos-dev
    - libhdf5-serial-dev

install:
  - pip install scipy shapely psutil
  - python setup.py develop

script:
  - python setup.py test
