sudo: false

language: python

python:
 - "2.7"

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libgeos-dev

install:
  - pip install psutil shapely
  - python setup.py install

script:
  python -m unittest discover -p *test.py
