sudo: false

language: python

python:
 - "3.4"

addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libgeos-dev
    - libhdf5-serial-dev

install:
  - pip install https://dl.dropboxusercontent.com/u/418677/scipy-0.16.0-cp34-cp34m-linux_x86_64.whl
  - python setup.py develop

script:
  - python setup.py test
