version: "3.7"

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 192.168.238.0/24
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 192.168.239.0/24

volumes:
  oqdata:

#definizione di un yaml template da usare poi negli altri servizi
x-op-service-default: &service_default
  restart: unless-stopped
  init: true

services:
  master:
    <<: *service_default
    container_name: engine-master
    image: openquake/engine-master-zmq
    ports:
     - 8800:8800
    # Uncomment to enable auth in WebUI/API
    # environment:
    #   - LOCKDOWN=true
    volumes:
     - oqdata:/home/openquake/oqdata
    # Uncomment to expose demos inside the container
     - ../demos:/home/openquake/demos:ro
    # Uncomment to use a local copy of the oq-engine
    #   - ../openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    # Uncomment to use a custom openquake.cfg
    #   - ./path/to/openquake.cfg:/etc/openquake/openquake.cfg
    networks:
     backend:
      aliases:
       - engine-master
     frontend:
     #labels:

  worker:
    <<: *service_default
    container_name: engine-worker
    image: openquake/engine-worker-zmq
    volumes:
     - oqdata:/home/openquake/oqdata:ro
    # Uncomment to use a local copy of the oq-engine
    #   - ../openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    # Uncomment to use a custom openquake.cfg
    #   - ./path/to/openquake.cfg:/etc/openquake/openquake.cfg
    networks:
     backend:
      aliases:
       - engine-worker
    depends_on:
      - master
