---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: yes
  become_user: openquake
  gather_facts: false

  tasks:
  - name: Copy job.zip to instance
    copy:
      src: job.zip
      dest: /home/openquake/
      owner: openquake
      group: openquake
      mode: '0644'

  - name: Run a Demo calc for EventBasedRisk
    command: /usr/bin/oq engine --run job.zip
    args:
      chdir: /home/openquake
    register: calc
  
  - debug: msg="{{ calc.stdout }}"

    # - name: Run database migrations
    #  command: env/bin/python migrate.py -q chdir=$project_dir/releases/$release_date
    #  register: result
    #  changed_when: result.stdout_lines

    #- debug: msg="{{item}}"
    #  with_items: result.stdout_lines
    #  when: result.stdout_lines
