# run with ansible-playbook -v -i host.linux /os_mgmt/ntp_linux.yaml --limit wks
#
- hosts: all
  #
  become: yes
  order: sorted

  roles:
      - oqengine

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

