---
name: demos
'on':
  push:
    branches: actions
  pull_request:
    branches: master 


jobs:

  docs:
    name: DOCS
    runs-on: ubuntu-latest
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      BRANCH: ${{ github.ref }}

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'


      - name: Upgrade pip and install openquake
        run: |
          pip install -U pip pytest
          pip install -r ./requirements-py38-linux64.txt
          pip install -e .

      - name: Run Hazard test
        run: |
          pytest --doctest-modules -xv openquake/baselib 
          OQ_DISTRIBUTE=no pytest --doctest-modules -xv openquake/hazardlib openquake/hmtk openquake/sep 
          pytest -vsx doc/adv-manual/developing.rst

      - name: Make latex docs
        run: |
          pip install sphinx==1.6.5
          sudo apt update; sudo apt-get install -y texlive-fonts-recommended texlive-latex-extra latexmk gpg
          cd doc/sphinx && make html && cd ../adv-manual && make html && make latexpdf


      - name: Shell for ssh
        env:
          DOCS_SSH: ${{ secrets.DOCS_ARTIFACTS }}
        run: |
          pwd
          gpg --quiet --batch --yes --decrypt --passphrase="$DOCS_SSH" --output ./.deploy_rsa ./.deploy_docs.enc
          chmod 600 ./.deploy_rsa
          eval $(ssh-agent -s) && ssh-add ./.deploy_rsa 
          cd doc/sphinx
          rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -ax --delete build/html/ docs@ci.openquake.org:/var/www/docs.openquake.org/oq-engine/master/ 
          rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -ax --delete build/html/ build/latex/OpenQuakeforAdvancedUsers.pdf docs@ci.openquake.org:/var/www/docs.openquake.org/oq-engine/advanced/;

  demos:
    name: DEMOS
    runs-on: ubuntu-latest
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      BRANCH: ${{ github.ref }}

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip and install requirements
        run: |
          pip install -U pip
          pip install -r ./requirements-py38-linux64.txt
          pip install fiona

      - name: Install oq engine 
        run: pip install -e . 

      - name: Upload oqdata.zip to  http://artifacts.openquake.org/travis/
        env:
          DOCS_SSH: ${{ secrets.DOCS_ARTIFACTS }}
        run: |
          zip -q -r /tmp/demos.zip demos/
          OQ_DISTRIBUTE=zmq bin/run-demos.sh demos/
          oq dump /tmp/oqdata.zip
          oq restore /tmp/oqdata.zip /tmp/oqdata
          helpers/zipdemos.sh $(pwd)/demos
          gpg --quiet --batch --yes --decrypt --passphrase="$DOCS_SSH" --output ./.deploy_rsa ./.deploy_docs.enc
          chmod 600 ./.deploy_rsa
          eval $(ssh-agent -s) && ssh-add ./.deploy_rsa 
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/demos.zip docs@ci.openquake.org:/var/www/artifacts.openquake.org/travis/demos-${BRANCH}.zip
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/oqdata.zip docs@ci.openquake.org:/var/www/artifacts.openquake.org/travis/oqdata-${BRANCH}.zip
