---
name: demos
'on':
  push:
    branches: actions
  pull_request:
    branches: master 
jobs:
  demos:
    name: DEMOS
    runs-on: ubuntu-1804
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      BRANCH: ${{ github.ref }}

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upload oqdata.zip to  http://artifacts.openquake.org/travis/
        shell: bash
        env:
          DOCS_SSH: ${{ secrets.DOCS_ARTIFACTS }}
        run: |
          echo
          echo "-- Environment variables ----------------------------------------------"
          env
          echo "-----------------------------------------------------------------------"
          echo "scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/demos.zip docs@ci.openquake.org:/var/www/artifacts.openquake.org/travis/demos-${BRANCH}.zip"
          echo "scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/oqdata.zip docs@ci.openquake.org:/var/www/artifacts.openquake.org/travis/oqdata-${BRANCH}.zip"
