---
name: demos
'on':
  push:
    branches: actions
  pull_request:
    branches: master 


jobs:

  artifacts:
    name: DEMOS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
      TRAVIS_COMMIT: ${{ github.sha }}
      BRANCH: ${{ github.ref }}

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install test dependencies.
        run: pip3 install -U pip3 pytest

      - name: Install oq engine 
        run: pip3 install . 

      - name: Upload oqdata.zip to  http://artifacts.openquake.org/travis/
        run: |
          zip -q -r /tmp/demos.zip demos/
          OQ_DISTRIBUTE=zmq bin/run-demos.sh $TRAVIS_BUILD_DIR/demos
          oq dump /tmp/oqdata.zip
          oq restore /tmp/oqdata.zip /tmp/oqdata
          helpers/zipdemos.sh $(pwd)/demos
          openssl aes-256-cbc -K $encrypted_806ab0daf95c_key -iv $encrypted_806ab0daf95c_iv -in $TRAVIS_BUILD_DIR/.deploy_rsa.enc -out $TRAVIS_BUILD_DIR/.deploy_rsa -d 
          chmod 600 $TRAVIS_BUILD_DIR/.deploy_rsa
          eval $(ssh-agent -s) && ssh-add $TRAVIS_BUILD_DIR/.deploy_rsa 
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/demos.zip travis@ci.openquake.org:/var/www/artifacts.openquake.org/travis/demos-${BRANCH}.zip
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/oqdata.zip travis@ci.openquake.org:/var/www/artifacts.openquake.org/travis/oqdata-${BRANCH}.zip
