---
name: docker
'on':
  push:
    branches:
      - multistagedocker
  schedule:
    - cron: "0 2 * * *"


jobs:
  docker:
    name: build and run a calc on docker compose infrastructure
    runs-on: ubuntu-latest

    steps:
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image engine with tag daily
        run: docker build -t openquake/engine:daily -f docker/Dockerfile.engine docker
      - name: List Image
        run: |
          docker image ls
      - name: Builds and load engine master with tags daily
        id: docker_master
        uses: docker/build-push-action@v2
        with:
          context: docker/zmq
          file: docker/zmq/Dockerfile.master
          tags: openquake/engine-master-zmq:daily
      - name: Builds and load engine worker with tags daily
        id: docker_worker
        uses: docker/build-push-action@v2
        with:
          context: docker/zmq
          file: docker/zmq/Dockerfile.worker
          tags: openquake/engine-worker-zmq:daily
      - name: Run docker compose to build up cluster
        run: |
          cd docker
          docker-compose -p oqcluster up -d
          sleep 30
          docker-compose -p oqcluster ps
