---
name: docker
'on':
  push:
    branches:
      - multistagedocker
  schedule:
    - cron: "0 2 * * *"


jobs:
  docker:
    name: build and run a calc on docker compose infrastructure
    runs-on: ubuntu-latest

    steps:
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image engine with tag daily
        id: docker_engine
        run: docker build -t openquake/engine:daily -f docker/Dockerfile.engine docker
      - name: List Image
        run: |
          docker image ls
      - name: Build image engine master with tag daily
        id: docker_master
        run: docker build -t openquake/engine-master-zmq:daily -f docker/zmq/Dockerfile.master docker/zmq
      - name: Builds image engine worker with tags daily
        id: docker_worker
        run: docker build -t openquake/engine-worker-zmq:daily -f docker/zmq/Dockerfile.worker docker/zmq
      - name: List Image
        run: |
          docker image ls
      - name: Run docker compose to build up cluster
        run: |
          cd docker
          docker-compose -p oqcluster up -d
          sleep 30
          docker-compose -p oqcluster ps
