---
name: docker
'on':
  push:
    branches:
      - multistagedocker
  schedule:
    - cron: "0 2 * * *"


jobs:
  docker:
    name: build and run a calc on docker engine 
    runs-on: ubuntu-latest

    steps:
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
	      id: vars
	      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and load engine with tag daily
        id: docker_engine
        uses: docker/build-push-action@v2
        with:
          context: docker 
          file: docker/Dockerfile.engine
          load: true
          tags: openquake/engine:daily

      - name: List Image
        run: |
          docker image ls

      - name: Builds and load engine master with tags daily
        id: docker_master
        uses: docker/build-push-action@v2
        with:
          context: docker/zmq
          file: docker/zmq/Dockerfile.master
          load: true
          tags: openquake/engine-master-zmq:daily

      - name: Builds and load engine worker with tags daily
        id: docker_worker
        uses: docker/build-push-action@v2
        with:
          context: docker/zmq
          file: docker/zmq/Dockerfile.worker
          load: true
          tags: openquake/engine-worker-zmq:daily

      - name: Run docker compose to build up cluster
        run: |
          cd docker
          docker-compose -p oqcluster up -d
          docker-compose -p oqcluster ps

