---
name: zmq
'on':
  push:
    branches:
      - multistagedocker
  schedule:
    - cron: "0 2 * * *"

jobs:
  docker:
    name: build and up compose 
    runs-on: ubuntu-latest

    steps:
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Image
        run: |
          docker image ls
      - name: Run docker compose to build up cluster
        run: |
          cd docker/tests
          docker-compose up -d
          sleep 30
          docker-compose ps
